### ISSUE TITLE
Bug in Redis install

### ISSUE THREAD

**Issue by corzel** [littlebizzy/slickstack#106]
Hi! 
There is a bug in redis install bash:
/var/www/ss-install-redis-packages: line 68: /var/www/ss-perms-redis: No such file or directory

Line 68= source /var/www/ss-perms-redis
But ss-perms-redis no longer exist. Now are ss-perms-redis-config & ss-perms-redis-packages.

**Comment by jessuppi** [comment]
Thanks for reporting @corzel 

We are still in the process of converting some hardcode lines into variables, but this issue is now fixed.

Ref: https://github.com/littlebizzy/slickstack/commit/4f6fa404c4e1d8ff11a217f4bf6ad7e6b243f847
Ref: https://github.com/littlebizzy/slickstack/commit/db1cf2f13ff3a524c895cf25911cf78710f40ed2
