### ISSUE TITLE
SS_WORDPRESS_MU_PLUGINS

### ISSUE THREAD

**Issue by kiwina** [littlebizzy/slickstack#109]
for some reason in the config file it ends up to be SS_WORDPRESS_WORDPRESS_WORDPRESS_WORDPRESS_WORDPRESS_WORDPRESS_WOR........._MU_PLUGINS

**Comment by jessuppi** [comment]
Thanks for reporting @kiwina 

Darn, probably too late to matter now since it may have messed up `ss-config` for those that had enabled custom plugins, but we did forcefully run `ss-update-config` right after you reported this, so it might be okay for those cases.

Anyway fixed, but it won't matter going forward: https://github.com/littlebizzy/slickstack/commit/62c60ebe97eaa00d74d0fb3f67d697f13e9d1ee5#diff-5220ddce97b73357f469fbd9cb5c49b0d76b58b81de145e33d18e6cc5e37814b
