### ISSUE TITLE
Updating PHP, MySQL and NginX

### ISSUE THREAD

**Issue by tinof** [littlebizzy/slickstack#11]
Thanks for this. I would like to upgrade PHP, MySQL and NginX. Any preferred method?

Dropping in MariaDB 10.4 works like a charm. PHP 7.3.5 does not. I have not tried NginX as I am sure everything will brake :)

**Comment by jessuppi** [comment]
Yes you can upgrade all packages as below:

`sudo bash /var/www/ss-update`

The package / upgrade situation is still being optimized. This is because some packages like Redis change so often that we don't want to use configuration boilerplates.

Anyway above method or `sudo apt update && apt upgrade` should both work fine. Any config changes that need to happen will be taken care of via cron jobs.

Yes we might replace MySQL with MariaDB in the near future, thanks --

**Comment by tinof** [comment]
Thanks for your reply.

If anyone has any idea how to replace PHP 7.2 with PHP 7.3 without breaking SlickStack, I would appreciate it.

**Comment by jessuppi** [comment]
> If anyone has any idea how to replace PHP 7.2 with PHP 7.3 without breaking SlickStack, I would appreciate it.

If you want PHP 7.3 then SlickStack is not for you. Our goal is all about stability and standards, and currently Ubuntu repos support PHP 7.2. Also, this is not a general support channel, become a paying member if you have lots of random technical support questions:

https://www.littlebizzy.com/members
