### ISSUE TITLE
The following plugins are disallowed on our network and have been deactivated

### ISSUE THREAD

**Issue by miketester19** [littlebizzy/slickstack#110]
Hello SlickStack;
First of all let me thank you for creating such a great Script, I've tested all of the scripts that includes, W0rdOps, Webinoly, EasyEngine etc. But I found the SlickStack script most secured and optimized, we all appreciate your efforts and hard work for providing us a great product.

Some thing happened and I started getting 403 error, then I ran ss update, and thanks to you guys, it resolved the issue.
But now I started having an other problem, activating WP-Rocket, Optimole and imagify. I'm sure some kind of permission problem I believe or may be some thing else that I'm missing.

Please help.
Thanks & Regards

**Comment by jessuppi** [comment]
Again, thanks for your kinds words but these are general questions and not bug reports, etc. Please become more familiar with our software or join our general chat rooms instead of posting on GitHub.

What your referring to is our MU plugin called Plugin Blacklist, which you can customize by specifying a custom source (URL) for a different plugin `blacklist.txt` file if desired using the `SS_WORDPRESS_PLUGIN_BLACKLIST_SOURCE` variable.

Or you can set the `SS_WORDPRESS_PLUGIN_BLACKLIST` variable to be `false` instead, too.
