### ISSUE TITLE
All of sudden certain files, directories got hidden

### ISSUE THREAD

**Issue by miketester19** [littlebizzy/slickstack#113]
Hello;
I was testing SlickStack on Vultr and Linode, I made modification to ss-config added new domain and ran ss-install.
And files under sites-available and some files under www and html got hidden. I check by typing, ls -a, and tried to unhide those files, but won't let me , even as root user.
Is this a bug? And it happened on both VPS.

Plus an other issue is the " Lack Of Support "  that I'm not supposed to mention it her, but I have to. We don't get support when we need it. I would highly request you , Please focus on that too. One of the biggest factor for any product to succeed is the Great Support. 

Thanks

**Comment by jessuppi** [comment]
@miketester19 SlickStack uses a custom location for Nginx server blocks: `/var/www/sites`

If you're trying to "hack" the Nginx configuration files, it will be overwritten. You need to edit `/var/www/ss-config` for all configuration settings you want, before running `ss-install` again.

If files are being deleted under `/var/www/...` that is probably due to user error, I assume. There shouldn't be anything that our installation process deletes under that directory path besides junk files via `ss-clean-files` etc.

So far you've:

- posted the same questions 4+ times in our various chat rooms
- posted general support questions on GitHub repeatedly after being asked to stop
- promised us you'd leave us a review on Capterra because you were so impressed (then you didn't)

This is not Burger King, it is a free software project, and your attitude is offensive. If you don't stop abusing our GitHub Issues with general support questions, we'll be forced to ban you...
