### ISSUE TITLE
ss-update-config delete custom mu-plugins

### ISSUE THREAD

**Issue by corzel** [littlebizzy/slickstack#114]
Hi!

It is not possible to have more than 19 mu-plugins and set false in blacklist plugin.

When I run ss-update-config only the first 19 items remain, so if I added in ss-config MU_PLUGIN_20_SOURCE, MU_PLUGIN_21_SOURCE... these are removed and SS_WORDPRESS_PLUGIN_BLACKLIST back to "true".

**Comment by jessuppi** [comment]
Thanks for reporting @corzel 

Not sure how, but seems we missed a few variables during the last commit... now fixed: https://github.com/littlebizzy/slickstack/commit/920d367cf9be723a195e9e184f763a841c0dbfab

This fix should address the issue of greater than 19 plugins not being copied over properly during ss-config updates. Sorry, some of these bugs are just due to settling of namespaces so that e.g. SlickStack could more easily support non-WordPress CMS applications the future, potentially. Eventually, it should be settled...
