### ISSUE TITLE
Fatal error due to leftover "tmp" folder in the mu-plugins directory

### ISSUE THREAD

**Issue by corzel** [littlebizzy/slickstack#115]
Hi!
I'm getting this error and notices in settings tabs. https://domain.com/wp-admin/admin.php?page=slickstack&tab=blacklist (&tab=cron, &tab=sftp, &tab=caching, etc.)

```
Fatal error: Cannot declare class LittleBizzy\Autoloader\Autoloader, because the name is already in use in /var/www/html/wp-content/mu-plugins/tmp/autoloader.php on line 34 
```
The cause of the fatal error is the last line in autoloader.php
```
// Autostart
new Autoloader;
```
If it's removed settings works again.

**Comment by jessuppi** [comment]
Hmm... I'm not sure why there is a `/tmp` folder inside your `mu-plugins` directory? It seems `autoloader.php` exists twice and that is causing a fatal error, it should only exist once (and definitely not in the /tmp/ child folder).

**Comment by jessuppi** [comment]
A follow up here... this was caused by a bug in `ss-install-wordpress-mu-plugins` that seemed to affect sites using a custom list of MU plugins in their `ss-config` file... in the past few months, I have done a lot of cleanup on that script.

Probably still some improvement to be had with how custom MU plugins are installed, but for now it should be working better and more importantly, the script will force delete the `tmp` folder every time it runs now.
