### ISSUE TITLE
Non ssl version is needed

### ISSUE THREAD

**Issue by bari86** [littlebizzy/slickstack#117]
Hi,
Can you direct or let me know how do I create a non https / non SSL version. I need to use non SSL for my WP. I am doing SSL offloading using haproxy and need to disable SSL. SSL will be perform externally. Does adjusting the Wordpress path in menu/database do the trick?

i see that it uses mu plugin force https. can I just disable that? and edit the wp path url.

**Comment by jessuppi** [comment]
@bari86 As per discussion on our chat server, this is not supported, and I don't wish to provide any guide to the public on how to disable SSL or anything like that because it will likely become outdated and users might refer to it, etc.

And really there is just no reason to support non-SSL in the case of SlickStack.

Both Cloudflare and Nginx already work as reverse proxies, and is our official recommendation. If you want to play with very complex tools, that is great, but not our goal here.

And the fact that you're not aware of how to disable SSL in Nginx (etc) is further proof that you probably shouldn't be doing it anyways. You would have to use custom Nginx configuration files and blocks, and pretty much disable the entire automated system that is SlickStack, meaning that doing so is pointless here really.
