### ISSUE TITLE
Cant install from 24 hours ago

### ISSUE THREAD

**Issue by sleeplife** [littlebizzy/slickstack#119]
Hi
I hve tested slickstack yesterday and it has been installed nicely, but today I cant

It stops at `Running ss-check: Retrieves latest ss core cron jobs and ss core bash scripts (except ss-check)... `

Even dont know whats going on

**Comment by jessuppi** [comment]
Hello @sleeplife 

Hmm sometimes there is a delay if GitHub is overloaded, etc. You can simply wait a few minutes and try again.

If you have a specific bug or error message please post it here, otherwise general Support questions should be posted in our community chat rooms e.g. Discord server instead of opening a GitHub Issue. Thanks!
