### ISSUE TITLE
Some warnings in php

### ISSUE THREAD

**Issue by socializam** [littlebizzy/slickstack#13]
Hello,

I have installed the slickstack github, all installation went ok.
In dashboard i see the following warnings in php error log.

PHP Warning: Invalid argument supplied for foreach() in /var/www/html/wp-cron.php on line 111
PHP Warning: include_once(/var/www/html/wp-content/functions.php): failed to open stream: No such file or directory in /var/www/html/wp-config.php on line 405
PHP Warning: include_once(): Failed opening '/var/www/html/wp-content/functions.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/wp-config.php on line 405

And so on everytime i click someting.

Any help is apreciated.
Thank you!

**Comment by jessuppi** [comment]
Hello, thanks for reporting this. By the way, your GitHub profile is setup incorrectly -- brands and companies should have an "organization" setup. We are encouraging everyone who continues here to maintain a real profile (name, photo, etc) to get away from the anon posts.

https://wordpress.org/support/topic/wp-cron-php-problem/

Lots of wp-cron errors reported lately in WP 5+ seems, reasons often unknown. It's possibly from one of the included MU plugins in SlickStack, but shouldn't be an issue.

Some of those errors only come because the installation process has not completed yet. You can try clearing the error log and reset permissions and see if that fixes it --

**Comment by socializam** [comment]
Hello, i have cleared the error log reset the permission, also doing things like chmod 777 and that is a bad thing to do still those errors occure.
Also removing all the mu-plugins did not resolve the errors.
What i did was removeing the wordpress installation (just for testing) and downloaded the wordpress from the official site, extracted to html folder setting the database db/pass etc in wp-config.php and the errors disappeared except the one for wp-cron.php and i understand that that's a issue in wp5+.
Anything i could try more?
Thank you!

**Comment by jessuppi** [comment]
Please come back after you've setup a real GitHub account (name, photo, etc) thank you --

**Comment by toaderrazvan** [comment]
@jessuppi that was not my account was a friends account and i can't change it. Do i close this issue and start a new one with the same problem?

**Comment by jessuppi** [comment]
> @jessuppi that was not my account was a friends account and i can't change it. Do i close this issue and start a new one with the same problem?

Thank you, please feel free to comment further on this thread, will close for now.

If it's not a recurring error its probably just a temporary error during the PHP install process...
