### ISSUE TITLE
Can the native Gutenberg page editor be enabled by default?

### ISSUE THREAD

**Issue by voidxd** [littlebizzy/slickstack#133]
Hi,

Could disabling Gutenberg be something optional? 

I use Gutenberg on some sites, and on others I disabled it.  I don't have the data to back it up, but if I had to guess, I'd say a great number of people use it.

Thanks!

**Comment by jessuppi** [comment]
Thanks for the suggestion @voidxd 

We have been brainstorming a lot during the past few years re: MU plugins. Part of the issue was making sure we didn't disrupt exist hosting clients and other less tech-savvy users who were used to our default configuration.

However, with PHP 8.1 approaching and Gutenberg getting more attention, we have hurried up and removed several of our default MU plugins from `ss-config` and `ss-install-wordpress-mu-plugins` as well:

Ref: https://github.com/littlebizzy/slickstack/commit/d9aa19ab4da54c8d6466123ceab72b6b62d1b0c0#diff-4d64b4bd0fb915a7eb351f1e19d1f6598da614286a93ca90a25367ca39bbd552

Ref: https://github.com/littlebizzy/slickstack/commit/15b61b79289ac5c97db494a273629da8fd8b04a2#diff-8f08b3c82ef4b6e55f3cfefe58833fb6ac3b809b68a1e96eb34f29ad86c874aa

Besides, some of our plugins haven't been updated in a while, and there are better plugins now for some of these functions such as Disable Gutenberg by Jeff Star, etc.

Anyway this is part of a broader conversation re: what we should include by default, so thanks for the feedback.
