### ISSUE TITLE
undefined variable "modified" in mu-plugin updater.php

### ISSUE THREAD

**Issue by backamblock** [littlebizzy/slickstack#145]
those 2 errors just popped up on top of my wp dashboard:

Notice: Undefined variable: modified in /var/www/html/wp-content/mu-plugins/clear-caches/helpers/updater.php on line 136
Notice: Undefined variable: modified in /var/www/html/wp-content/mu-plugins/force-https/helpers/updater.php on line 136

and here they are again when updating a plugin :) The update did work tho

![image](https://user-images.githubusercontent.com/20801141/150907240-491358fe-3453-438b-8fda-2eab82d38f64.png)

**Comment by jessuppi** [comment]
Thanks @backamblock but this Issue already exists (please search before opening a new Issue):

Ref: https://github.com/littlebizzy/slickstack/issues/59

I think this might be caused by a PHP namespace conflict... it's not serious, but just annoying. Anyway the MU plugins that we use are separate repos (LittleBizzy plugins) which are in need of revamping.
