### ISSUE TITLE
Buggy javascript in WooCommerce elements (page scrolling down)

### ISSUE THREAD

**Issue by smickys** [littlebizzy/slickstack#153]
Hello,

There is a strange issue with Wordpress JS. When I choose variations on a product page it scrolls down a page. It's not just with variations, it's also with few other atributes.
When you're at the top of the page, this bug is not performing, first you need to scroll down by 3 indexes.
https://shop.dvaraka.lt/parduotuve/maistas/kepiniai/dvarakos-namine-duona/

You can find this issue here too:
https://shop.dvaraka.lt/apmokejimas-ir-pristatymas/

**Comment by jessuppi** [comment]
@smickys As per our discussion on Discord, this is most likely a problem with your theme itself.

You can narrow it down by removing all MU plugins, disable all normal plugins, and/or testing a different theme --

**Comment by jessuppi** [comment]
Update: as suspected, this was caused by your page builder, Elementor Pro.

For any future readers, do please disable ALL plugins, and try changing your theme, if you have seeing any frontend conflicts related to javascript (etc)... in most cases, it's theme or page builder related, although in rare cases it could be something caused by one of SlickStack's MU plugins (or even CloudFlare).
