### ISSUE TITLE
Mysql Data got reset

### ISSUE THREAD

**Issue by madc0de** [littlebizzy/slickstack#162]
Like how the heck all my MySQL Data got reset yet the database exists??

So, I installed SlickStack, migrated my old site to my new server where slickstack is setup after I week I visit my site and I see a prompt to install wordpress.

How and why is this happening?

**Comment by madc0de** [comment]
So, I just realized something.

I had installed march version of slickstack and current build is april. So the update may have done this.

Can you please verify @jessuppi

**Comment by jessuppi** [comment]
Hey @madc0de thanks for sharing here...

If the database still exists, and the credentials work fine, there is only one possible cause: your team must have "hacked" the wp-config.php file and/or changed the table prefix being called by WordPress.

Remember that you can't edit or customize wp-config.php because SlickStack will overwrite your changes during next installation or update based on `ss-config` settings.

This is more of a general support request (not a bug report) so please follow up in our Discord chat room.
