### ISSUE TITLE
ss-sync-staging excluding any file with "uploads" in the filename

### ISSUE THREAD

**Issue by BHare1985** [littlebizzy/slickstack#167]
Wordpress broke when I installed elementor and synced to staging.

the elementor file `wp-content/plugins/elementor/core/files/uploads-manager.php` was being excluded from the sync.

Issue was an over-reaching exclude in the rsync in ss-sync-staging  the command  `ss_rsync --max-size=5mb --exclude="mu-plugins*" --exclude="uploads*" /var/www/html/wp-content/ /var/www/html/staging/wp-content`   should use `--exclude="/uploads/*"`  or `--exclude="uploads/*"` instead of a wildcard of any file with the word uploads.

**Comment by jessuppi** [comment]
Another update... here's how it looks now in `ss-sync-staging` script:

    ## copy wp-content files over (skips media uploads) ##
    ss_rsync --max-size=5mb --exclude 'blacklist.txt' --exclude 'object-cache.php' --exclude mu-plugins --exclude temp --exclude upgrade --exclude uploads /var/www/html/wp-content/ /var/www/html/staging/wp-content

Ref: https://github.com/littlebizzy/slickstack/blob/master/bash/ss-sync-staging.txt

Likewise in `ss-push-staging` it now looks similar:

    ## copy wp-content files over (skips media uploads) ##
    ss_rsync --max-size=5mb --exclude 'blacklist.txt' --exclude mu-plugins --exclude temp --exclude upgrade --exclude uploads /var/www/html/staging/wp-content/ /var/www/html/wp-content

Ref: https://github.com/littlebizzy/slickstack/blob/master/bash/ss-push-staging.txt

The `object-cache.php` file should never exist in staging, therefore it's not included for exclusion here... 

Also, I've just added the `--no-links` flag to our `ss_rsync` bash aliases now, SlickStack only uses `rsync` for unpacking e.g. WordPress ZIP files or syncing/pushing staging sites, so it should be fine to use it here since we want to ignore the symlink pointing to the `/uploads/` directory that exists in the staging site just to be sure.

Ref: https://github.com/littlebizzy/slickstack/commit/9a81d5d49fff39ccc4acc4aefced214286a36713

**Comment by jessuppi** [comment]
I ran some tests and the exclusion rules seem to be working correctly now... also some tweaks in `ss-perms-wordpress-core` to ensure that `/uploads/` is a symlink for staging sites, etc.

Ref: https://github.com/littlebizzy/slickstack/blob/master/bash/ss-sync-staging.txt
Ref: https://github.com/littlebizzy/slickstack/blob/master/bash/ss-perms-wordpress-core.txt

I'm going to close this for now, if any other syncing problems please open a new Issue or for any follow-up comments anyone is free to comment below. Thanks!
