### ISSUE TITLE
PHP Warning: include_once(/var/www/html/wp-content/functions.php): failed to open stream: No such file or directory in /var/www/html/wp-config.php on line 410

### ISSUE THREAD

**Issue by ERenna** [littlebizzy/slickstack#17]
Hello,

I've just installed SlickStack successfully on my VPS (Ubuntu 18.04 - 4GB RAM).
It's running smoothly, but I'm getting a persistent error logged by PHP Error Log in Wordpress' dashboard.

Here you go:
PHP Warning: include_once(/var/www/html/wp-content/functions.php): failed to open stream: No such file or directory in /var/www/html/wp-config.php on line 410

"wp-confing.php" is trying to include a "functions.php" that should be inside the "wp-content" folder. The real problem is that, there should't be a functions.php file in that folder. At least, vanilla wordpress doesn't have that file.

I hope there's a solutions to it.
If you need further info, I'm available

**Comment by jessuppi** [comment]
Okay that `functions.php` file is used by the Custom Functions MU plugin so that developers can add custom PHP functions to WordPress without hacking their theme or `wp-config.php` file.

We've added a patch to ensure it exists in `ss-muplugs`

The `ss-install` runs the MU plugins installer, and it also runs 1x each day using cron jobs too, so either way it should now always exist even if the Custom Functions plugin fails to create it.

Ref: https://github.com/littlebizzy/slickstack/commit/2c77f8b843745768516b81127a47bc4498d407e7

Either wait for ~24 hours or run `ss-muplugs` right now manually...
