### ISSUE TITLE
File permission issues and 403 Forbidden

### ISSUE THREAD

**Issue by AlexCroydon** [littlebizzy/slickstack#174]
Hello all, 

After just clean install I have got an 403 Forbidden
I logged in from SFTP user and I have noticed that folder 
cache folder
owner 
33[33] 
group 
33[33]
As well as folder html owner and all sub folders  
owner
1001 [1001] 
group 
1001 [1001]

Thanks for help

**Comment by jessuppi** [comment]
Hello @AlexCroydon 

GitHub issues are for bug reports and feature requests, not general support. Please join our free Discord chat server if you have general questions about using SlickStack.

I'm not sure I understand your owner/group comments, but the 403 Forbidden error is probably because you are trying to load the `/wp-admin/install.php` URL which is blocked for security reasons, you can run `ss-install-wordpress-core` again to try and populate the WordPress database to avoid the redirecting to that URL.
