### ISSUE TITLE
Slick Satck Cache issue in wordpress

### ISSUE THREAD

**Issue by Mustaqeem-rgb** [littlebizzy/slickstack#176]
On my WordPress website PHP OPcache: enabled and after every new post i have to clear cache on this url  "domain-name/wp-admin/options-general.php?page=clear-caches"  otherwise my post would not display on site. How i can fix this issue?

**Comment by jessuppi** [comment]
@Mustaqeem-rgb Thanks for your feedback, however this is for bug reports and feature requests. Please bring you general questions to our Discord server or Skype group chat instead.

Briefly, since SlickStack doesn't use per-URL purging you will need to purge cache to see immediate homepage updates... this doesn't matter for brand new content pages.

**Comment by Mustaqeem-rgb** [comment]
This is also a bug if i have to purge cache after every new post, can you
assist me to resolve this?
