### ISSUE TITLE
FCGI_BUFFERS default value 16 16k causing Nginx to fail

### ISSUE THREAD

**Issue by damiafaw** [littlebizzy/slickstack#179]
Hello,
Please change the following line in ss-config as nginx is failing to start due to the following error
nginx: [emerg] "fastcgi_busy_buffers_size" must be less than the size of all "fastcgi_buffers" minus one buffer in /etc/nginx/nginx.conf:281
nginx: configuration file /etc/nginx/nginx.conf test failed

FCGI_BUFFERS="16 16k"

to

FCGI_BUFFERS="32 32k"

**Comment by jessuppi** [comment]
Awesome work thanks @damiafaw 

So just for Google, if using `fastcgi_busy_buffers_size 256k;` then you have to use at least `32 32k` for `fastcgi_buffers` otherwise Nginx fails to start with the error you mentioned...

So, back to the original default values we had set in the `ss-config` boilerplate, at least this is now publicly documented now because before I couldn't remember why we had those values as default, and later I even commented the buffer settings out in `nginx.conf` perhaps for a similar reason, just lack of complete testing.

This is what `ss-config` boilerplate looks like now:

```
FCGI_BUFFERS="32 32k" ## 16 16k not compatible with 256k busy buffers
FCGI_BUFFER_SIZE="32k"
FCGI_BUSY_BUFFERS_SIZE="256k"
FCGI_TEMP_FILE_WRITE_SIZE="256k"
```

**Comment by jessuppi** [comment]
The backstory here is that we had all been discussing this on Discord the past few days. Also, this is a great example of random things we can add to our new anonymous forum:

https://slickstack.io/forum/topic/why-does-slickstack-use-32-32k-value-for-nginx-fastcgi_buffers

e.g. When we don't have time to update docs, but need things to be public.
