### ISSUE TITLE
Error 400 when importing a demo theme.

### ISSUE THREAD

**Issue by ERenna** [littlebizzy/slickstack#18]
Hello,

I'm getting a 400 Error when trying to import any demo with the following theme: GeneratePress.

I've tried to use it on another VPS without SlickSlack, and the import works.
I've searched for a solution on internet without any result.
Any suggestion?

**Comment by jessuppi** [comment]
You'd have to ask the author of that theme, as the 400 error is generated by their server.

You can also try to reset permissions to be sure using `ss-perms` although it runs every few hours in SlickStack by default via cron jobs...

Please consider completing your GitHub profile (photo, etc) so that we can grow a more professional and transparent community here, thanks for your feedback --
