### ISSUE TITLE
Consider replacing Nginx with Caddy

### ISSUE THREAD

**Issue by hj-collab** [littlebizzy/slickstack#184]
Hi.

We have recently migrated all ours servers to Caddy from Nginx after going through a extensive testing of year.

It's as performant as Nginx. Comparing latest version of both but written in memory safer language (Go), have the best native implementation to handle TLS cert operations, saner defaults compared to Nginx outdated default configs (we had to tweak nothing to be honest), http/3 support out of box, config syntax is more readable and their team is helpful.

**Comment by jessuppi** [comment]
Hello @hj-collab and thanks for the suggestion.

Have you tried SlickStack yet? I ask because sometimes people come through with requests for major feature changes before they've tested our existing configuration yet... your account also has no history.

Are you doing marketing work for @caddyserver or something? If so, it would be better for real names.

**Comment by jessuppi** [comment]
Anyway instead of just going through GitHub repos tagged #nginx and telling them to use Caddy, it would be a lot more helpful to test our specific stack and see if it's compatible.

Because Caddy is so tightly knit, I'm not even sure it could be swapped in to SlickStack.

**Comment by jessuppi** [comment]
Okay then,

> I had tested SlickStack with many other stacks in the past but couldn't continue with it due to single site limitations. 

But this wouldn't change per se just from using Caddy, it's the vision of our project.

> Caddy does not incorporate caching or rate limiting capabilities in the core and you will need to build it with the respective modules. 

This alone would probably disqualify Caddy from being a good match for our project, as some fairly high-traffic sites have used SlickStack and some nitty-gritty settings are sometimes desired. Currently we can do all of this using the bundled features of Nginx in the `nginx-extras` package maintained by Ubuntu... no compiling required.

I haven't played with Caddy but from my understanding, the SSL/Let's Encrypt feature is the big selling point. Granted that is always nice to have things automated but it also means you can't adjust it.

Caddy is also still a newer project I think, with a small team... our team is also small, so having multiple components of our stack relying on small teams does not instill as much confidence about longevity, etc. It's part of the reason I chose MySQL instead of MariaDB, as stability is really our most valued aspect.

I imagine there are other things that Caddy might get us boxed into... it just doesn't seem to hold to the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) or play very nice with other components.

And in a few more Nginx releases, some of these advantages might disappear... I try not to chase the latest and greatest software and value long-term stability above all else.

**Comment by jessuppi** [comment]
Closing this for now, but future comments are welcome re: Caddy, thanks!

**Comment by jessuppi** [comment]
https://slickstack.io/forum/topic/would-slickstack-ever-consider-using-caddy-not-nginx
