### ISSUE TITLE
change php version and Install ioncube loader

### ISSUE THREAD

**Issue by bahreynipour** [littlebizzy/slickstack#188]
Hi There, 
I installed ss on a vps, But I need to have ioncube loader for my website to work properly. Can you help me please?
Also, Would you please help me to change php version to 8?

**Comment by jessuppi** [comment]
Hello @bahreynipour some of this sounds like general support questions, which is better suited to our Discord server, please consider sponsoring SlickStack and joining us there.

About Ioncube, it requires custom lines to be added in `php.ini` and SlickStack doesn't support that currently. I'm not sure if we'd want to support it, truthfully.

Ref: https://slickstack.io/forum/topic/add-ioncube-extension-to-php

**Comment by jessuppi** [comment]
About PHP version, SlickStack only supports the current version from Ubuntu LTS:

- Ubuntu 22.04 is PHP 8.1
- Ubuntu 20.04 is PHP 7.4
- Ubuntu 18.04 is PHP 7.2
- etc

As we avoid compiling packages, there is no way around this and it's how SlickStack is meant to work. If you want a different PHP version you need to install a different Ubuntu LTS on your server.

**Comment by jessuppi** [comment]
https://slickstack.io/forum/topic/how-can-i-downgrade-php-version-from-8-1-to-7-4

**Comment by jessuppi** [comment]
It's been a long time since I used ionCube but I'm pretty sure the main purpose is still the same, which is hiding code from your customers to prevent them from seeing it. This pretty much goes directly against WordPress and SlickStack philosophy, and I can't think of any good reason to support ionCube for now.

See: https://www.liberiangeek.net/2018/09/ioncube/

> By using proprietary software such as an IonCube to lock down programming code built with a free open source language like PHP, you are directly violating the spirit of what built PHP in the first place.
> 
> By some users and developers, you might be seen as a cynical exploiter of other people’s work and generosity, since you are using open source platform (PHP) to create closed source proprietary code.
> 
> Depending on the project you are working on, locking down your PHP code could potentially cause more problems than it solves. It could potentially create negative feelings about your software product, turn off talented developers who might contribute to your project, or reduce the innovation you might receive by keeping your code open source.
> 
> At its worst, using PHP code lockdown software like IonCube could potentially attract hackers who are determined to mess with your project just to be ornery and contrary towards anyone violating the spirit of open source.
> 
> While this last scenario is not very likely, it is worth considering whether the public relations aspects of violating open source philosophy is worth the additional code “security.”

There have also been malware attacks on WordPress sites in the past with files pretending to be ionCube, a sort of poetic attack that hurts developers who were trying to hide their code from users...

Ref: https://threatpost.com/wordpress-users-warned-of-malware-masquerading-as-ioncube-files/130103/

For now, I'm going to close this and say SlickStack doesn't support ionCube for now, and probably we won't support "hacking" the `php.ini` either since there's no other reason to that I'm aware of. Thanks --
