### ISSUE TITLE
sudo user and sftp user

### ISSUE THREAD

**Issue by skygunner** [littlebizzy/slickstack#192]
Maybe the script should warn the user shall not use the same account for sudo and sftp. 
After the setup, sftp user does  not allow to login.

**Comment by jcroy** [comment]
Yeah same thing happened to me the first time just breezing through the install. Then I go to ssh and was like huh, I know I saved all values correctly.

**Comment by jessuppi** [comment]
Thanks for your feedback @skygunner and @jcroy 

This should no longer be an issue because SlickStack now generates random usernames during installation, with the exception of the sudo user which can be manually specified in the wizard. 

However I've updated comments in ss-config to make things a bit more clear to new users:

`## SUDO_USER = [*must be unique*] username for SSH (must be different than SFTP_USER) ##`

Ref: https://github.com/littlebizzy/slickstack/commit/8e0d0d2ac090bd4d9226fad8c44a9ee7788b8f2d
