### ISSUE TITLE
SFTP file upload for owner www-data 

### ISSUE THREAD

**Issue by skilver-io** [littlebizzy/slickstack#26]
Hey,

Trying to get my head around this simple question and don't want to mess with any permission etc. on this clean ss installation.

I am trying to replace the file _apple-developer-merchantid-domain-association_ within the directory _www/html/.well-known_. However, the sftp user doesn't have writing permission to that file since it's owner is www-data. 

Stripe asks me to replace this file in order to get the Apple Pay feature activated on my WordPress and WooCommerce installation.

What is the best way to replace this file?

Once again, thank you for this stack and your work. I really appreciate it!

Best,
Dennis

**Comment by jessuppi** [comment]
Hmm, okay it looks like we had conflicting permissions in `ss-encrypt` and `ss-perms`... these have now been corrected and matched with each other. The strange thing is that your permissions should have been `SFTP_USER:wordpress` on that folder after installation completed, anyways. 

Anyway now it should be fixed, so that both SFTP user and server (e.g. Cerbot, coming soon) can properly use that folder and add/modify files as needed.

https://github.com/littlebizzy/slickstack/blob/master/ss-perms.txt#L129
https://github.com/littlebizzy/slickstack/blob/master/ss-encrypt.txt#L60

```
## this folder used by server for e.g. Cerbot but also SFTP for things like Stripe ##
chown -R $SFTP_USER:www-data /var/www/html/.well-known
chmod 6775 /var/www/html/.well-known
```

**Comment by skilver-io** [comment]
Great, everything works now after reinstalling the slickstack.

Thank you.
