### ISSUE TITLE
False positive issue

### ISSUE THREAD

**Issue by ttodua** [littlebizzy/slickstack#28]
(topic migrated from : https://spectrum.chat/slickstack/general/hello-there-is-false-positive-in-one-script~791c073b-3119-452a-9ee4-e7a16138135a  )

Hi.
I am maintainer of our firm plugins (Puvox.Software), and I've seen that SlickStack markes it's files as "malware".
I think if on our websites, blogs and in all our plugins, we announced that SlickStack is malware and malicious software - you would feel offended. Would it be nice?

None of our plugins are malware and neither their containing parts. Especially the main library file, which is marked as "known malware".
Please, show us any case or code part that it's malware (even in revision history of any file).
I hope that was done non-deliberately. So, please revert that and denounce our plugins are "malware".

1) if you search for "default\_library\_puvox.php", it's accused of being "malware":
http://mirrors.slickstack.io/ss-clean.txt

Please provide proof for the accusation, it is a simple lie. If you don't know what is the term "malware", then you should be such easily using that against of what you don't like. File had none of malware behavior ever, and is shared library class for all our plugins. There are many famous plugins that create their files in different folders (inside "wp-content") and it's allowed to create files inside "wp-content" (theorically, even if not "best-recommendation", but still allowed. And in our case, it's essential for your shared plugins).

2) here if you search for word "wp-phpmyadmin-extension", it's accused of instability or like that:
http://mirrors.slickstack.io/ss-clean.txt

That's totally false, as there is no HOOK in plugin that hooks into wordpress. the plugin is only executed if user enters in separate Dashboard settings page of plugin.

and also in :
http://mirrors.slickstack.io/wordpress/blacklist.txt

#
Personally me, I've put enormous time to develop those plugins (especially integrating PhpMyAdmin into wordpress, primarily taking care of it's security), and it was bad when I saw your software-parts with mentioned glitches.
So, at first, I just ask to revise the false accusations (I am sure they are mostly done nondeliberately, but even though it should be fixed). If you ever found any problem with plugin, you know how professionals behave - they report to plugin author if there is any issue, moreover security (if you cared of security of users, could have reported it to us), but that wasn't done, showing the obvious signs of nonstandard practice.

**Comment by jessuppi** [comment]
Hello @ttodua and I'm sorry for labeling that file incorrectly as malware, I believe we found that file during a malware infection and assumed it was part of the infection because we couldn't find any reference about it online.

That line has now been commented out, and will be changed later:

Ref: https://github.com/littlebizzy/slickstack/blob/master/bash/ss-clean-files.txt

However about "wp-phpmyadmin-extension" and any other phpMyAdmin related scripts, SlickStack deletes all of them because our stack bundles the Adminer script already directly from the source. For our purpose "creates instability" doesn't mean the code is bad or anything like that per se, it's just a reference to possibly conflicting with another feature, etc.

Thanks for commenting and please feel free to add any future thoughts on this page.

**Comment by jessuppi** [comment]
> That line has now been commented out, and will be changed later:

Deleted entirely now:

Ref: https://github.com/littlebizzy/slickstack/commit/87947e078ca28f35b115abb129dd2a33a05772b3
