### ISSUE TITLE
sshd_config deprecated options Ubuntu 20.04

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#35]
/var/log/auth.log gets filled with 

May  3 12:55:56 localhost sshd[109454]: rexec line 31: Deprecated option UsePrivilegeSeparation
May  3 12:55:56 localhost sshd[109454]: rexec line 34: Deprecated option KeyRegenerationInterval
May  3 12:55:56 localhost sshd[109454]: rexec line 35: Deprecated option ServerKeyBits
May  3 12:55:56 localhost sshd[109454]: rexec line 60: Deprecated option RSAAuthentication
May  3 12:55:56 localhost sshd[109454]: rexec line 67: Deprecated option RhostsRSAAuthentication
May  3 12:55:56 localhost sshd[109454]: error: Unable to load host key: /etc/ssh/ssh_host_dsa_key

**Comment by jessuppi** [comment]
@Bronislawsky Thanks for reporting and for the clear Issue title as well.

This should now be fixed with latest `sshd_config` template:

https://github.com/littlebizzy/slickstack/blob/master/ubuntu/sshd-config.txt

I'm still reviewing a few possible tweaks, but if anyone has suggestions to the SSH config they can create a new Issue with specific suggestions. Thanks!
