### ISSUE TITLE
mu-plugins - maintenance-mode - inaccessible frontend

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#45]
Hi, out of curiosity, when I turn on maintenance, I get this message

**Notice: Maintenance Mode is currently enabled, and the frontend is inaccessible to unprivileged users. View Settings**

But as a admin, I would guess I am a privileged  user, but I still get the "We’ll be back online as soon as possible." page, I have no frontend access. is that normal ?

**Comment by jessuppi** [comment]
@Bronislawsky Thanks, we never completed that feature.

If you can open this Issue on the appropriate plugin repo instead it would be great:

https://github.com/littlebizzy/maintenance-mode

**Comment by jessuppi** [comment]
We ended up removing Maintenance Mode from our default MU plugins, because the feature didn't seem very popular with most of our users (it seemed to generate confusion more than anything), and because SlickStack now has a bash script made for this instead called `ss-maintenance-on` and `ss-maintenance-off` ... being server-based means that it can work regardless of whether or not WordPress is installed/working/caching properly, which seems more appropriate.

For WordPress-based solutions, please use your favorite maintenance plugin.
