### ISSUE TITLE
Typo in ss-install and ss-check dos2unix file permissions

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#46]
Hello!
ss-install:218:mkdir touch /var/www/meta/.ssh
mkdir should not be there I beleive
and  ufw allow @SSH_PORT should be ufw allow $SSH_PORT
no big beal also because users.rules override this

Also
in ss-check dos2unix change de permission of ss and cron files
I dont think its a big deal, but ss-perms and ss-check fight for their permissions :)

**Comment by jessuppi** [comment]
Thanks @Bronislawsky 

`ss-install` is still pretty messy, I've saved it for last as far as optimization goes. Those typos that you mention have been fixed in the below commit:

Ref: https://github.com/littlebizzy/slickstack/commit/3aa1aa04ec70b2418bfa321291f9754827594f80

The perms conflicts have also been fixed in these 2 commits:

Ref: https://github.com/littlebizzy/slickstack/commit/0bb62b8e11a27ac0e243edd768ac17b1418fc064
Ref: https://github.com/littlebizzy/slickstack/commit/4a57e4c4ef170c83bcd032656f02962422103249
