### ISSUE TITLE
Warning: Use of undefined constant https - xxx-notices.php

### ISSUE THREAD

**Issue by gbozzetti** [littlebizzy/slickstack#50]
Hello,

Since yesterday I see this new warning in the error log:

PHP Warning: Use of undefined constant https - assumed 'https' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/mu-plugins/xxx-notices.php on line 68

I think you can fix the problem using quotes:

instead of $prod_link = home_url( $path = '', $scheme = https ); use 
`$prod_link = home_url( $path = '', $scheme = 'https' );`

Thank you!

**Comment by jessuppi** [comment]
Thanks for your report @gbozzetti 

This is now fixed in both `xxx-notices.php` and `xxx-staging.php` as per following commits:

Ref: https://github.com/littlebizzy/slickstack/commit/c310d313817b39aa0ebb3794932899d0f66e31bb
Ref: https://github.com/littlebizzy/slickstack/commit/80d13218a5ff53a352b29ee512869b927a8972de

Please feel free to submit pull requests directly to Master for small bug fixes like this in the future if you'd like to be listed on GitHub as a contributor to our FOSS project. Thanks!
