### ISSUE TITLE
PHP Warning: chmod() on class-wp-filesystem-direct.php

### ISSUE THREAD

**Issue by gbozzetti** [littlebizzy/slickstack#52]
Hello,

I see this warning in the error log file, but I don't know what is generating it, could you tell me if slickstack is interacting in someways with this wordpress file?

Anyway it looks something related to permissions:

PHP Warning: chmod(): Operation not permitted in /var/www/html/wp-admin/includes/class-wp-filesystem-direct.php on line 168

Thank you!

**Comment by jessuppi** [comment]
Thanks @gbozzetti 

This was possibly a temporary issue while we were optimizing our `ss-perms` (reset permissions) core script. Please let me know if you are still seeing any permissions-related errors?

Ref: https://github.com/littlebizzy/slickstack/blob/master/ss-perms.txt

From my understanding, most similar permissions errors given by `class-wp-filesystem-direct.php` are due to file ownership conflicts, but this should not be an issue with SlickStack default permissions:

Ref: https://wordpress.org/support/topic/warning-chmod-operation-not-permitted-in/
Ref: https://wordpress.stackexchange.com/questions/362995/wordpress-update-fails-with-a-permission-error
