### ISSUE TITLE
ss-dump mysqldump

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#56]
Here is what I noticed when I run ss-dump

this line ---> mysqldump --user=root --host="$DB_HOST" --protocol=tcp --port=3306 --dump-date --flush-privileges --force "$DB_NAME" > /var/www/meta/wp.sql

root@localhost:/var/www# ./ss-dump 
Dumping the live MySQL database to /var/www/meta/wp.sql...
mysqldump: Got error: 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES) when trying to connect
SUCCESS! The MySQL database was dumped to /var/www/wp.sql.

I got this error,
if I remove    --host="$DB_HOST" --protocol=tcp --port=3306
it dumps well no warning.
./ss-dump 

Dumping the live MySQL database to /var/www/meta/wp.sql...
SUCCESS! The MySQL database was dumped to /var/www/wp.sql.
root@localhost:/var/www#

**Comment by jessuppi** [comment]
Thanks @Bronislawsky 

So this is related to other ongoing issues with our upgrade to MySQL 8.0. There were breaking changes to `mysqldump` that happened first in MySQL 5.7, and then breaking user authentication/etc issues twice so far in early 8.0.x versions.

Anyway, this should now be fixed with latest changes to our Bash functions (aliases) and `ss-dump`

Ref: https://github.com/littlebizzy/slickstack/blob/master/ss-dump.txt

In summary, adding `--no-tablespaces` to `mysql` dump avoids certain privilege-related errors in MySQL 5.7.x and 8.0... also, requiring the TCP protocol is still necessary in order for `ss-dump` to support remote databases:

```
function mysqldump {
    command mysqldump --user=$DB_USER --password=$DB_PASSWORD --host=$DB_HOST --protocol=tcp --port=3306 --no-tablespaces --single-transaction --skip-lock-tables --dump-date --force "$@"
}
```

The handy `export MYSQL_PWD=$DB_PASSWORD` approach is also now deprecated in 8.0 so for now I've put the password variable back inside the inline options... janky but it works, until we consider more re: options files, or etc.

Last note here is that forcing the `--databases` flag also avoids confusion re: tables:

`mysqldump --databases $DB_NAME > /var/www/meta/wp.sql`

Several new public references added to bottom of `ss-dump` with more explanation of these issues. Thanks!
