### ISSUE TITLE
Multiple errors installing on DediPath server (Ubuntu 20.04)

### ISSUE THREAD

**Issue by nichlashansen** [littlebizzy/slickstack#60]
Pasted all terminal print: https://paste.ee/p/hTRHC
Host: Dedipath
Server: Intel Xeon E5-2630L - 4GB RAM - 250GB HDD Hybrid dedicated server

Installed Mysql before running the slickstack script.
Looks like the script is uninstalling the Mysql and failing installing some of the dependencies and configuring them.

**Comment by jessuppi** [comment]
Hey @nichlashansen sorry for not commenting here earlier... I can't remember if we discussed this already on on our old Facebook group or something like that.

It looks like your paste link is expired, if possible you can copy errors directly here on GitHub next time.

I haven't done much testing on dedicated servers, most of our testing is on KVM cloud servers on some of the major providers like DigitalOcean, Vultr, Linode, Hostwinds, UpCloud, Hetzner, etc.

For now I will close this Issue because I'm not sure what the error was exactly, but please comment here if you have any more information on this. Re: packages, sometimes it depends on the hosting provider's mirrors.

**Comment by jessuppi** [comment]
Btw looks like Dedipath actually has KVM machines, maybe I will test it later:

https://dedipath.com/ssd-kvm-vps

**Comment by jessuppi** [comment]
A final note here:

> Installed Mysql before running the slickstack script.
> Looks like the script is uninstalling the Mysql and failing installing some of the dependencies and configuring them.

Yes, it's probably not a good idea to install MySQL separately, just let SlickStack do it. As far as MySQL packages and configuration this has also been vastly improved in the few years since you posted, so if you can please try again and let us know if any errors exist on DediPath we can take a more detailed look. Thanks!
