### ISSUE TITLE
Cache configuration on top of the stack (redis, fast-cgi, etc.)

### ISSUE THREAD

**Issue by gabrielstuff** [littlebizzy/slickstack#68]
Hello,

I've noticed that there is already a cache mecanism installed and which looks performant.
Testing a demo site against the stack, I've noticed that they propose some improvement 🚀 : 

-https://tools.pingdom.com/#5d519f5747800000
- https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fune-apres-midi.fr%2F&tab=desktop

It is mainly related to minification and compression.

In the past, I've always used WpRocket, what is your recommandation here ? Simply configure cloudflare with minification ? 

What would you recommand ?

Thanks again for this amazing boilerplate.

**Comment by jessuppi** [comment]
@gabrielstuff Sorry it seems I missed this Issue for some reason. 

Anyway GitHub is for bug reports and feature requests, please bring general Support questions to our chat rooms.

Google PageSpeed is extremely biased really, and mostly just a way for Google to promote their Webp image format and accompanying web browser, Chrome. I never really use their tools anymore for that reason.

As I tell everyone far and wide, Webp is still not a web standard, and shouldn't be used in place of JPEG, etc unless it's done at the CDN level via on-the-fly conversion like Cloudflare etc does.

We don't recommend any cache plugins because Nginx FastCGI cache is enabled already. Cache plugins are just adding more bloat to your PHP processes and database.

But yes, basic minification of HTML or inlining CSS styles is something we support.
