### ISSUE TITLE
Setting a specific time to run the mu-plugins script

### ISSUE THREAD

**Issue by corzel** [littlebizzy/slickstack#76]
Hello!

I want to ask for add an option to set a specific time to run the mu-plugins script. 

Right now, on my server this is running at 1:14 PM. and it takes less than a minute to complete the process, but during these seconds the site becomes inaccessible. So I prefer to change this to run after midnight when there are no visitors.

Regards.

**Comment by jessuppi** [comment]
Hello thanks for your feedback @corzel 

I think this touches on a bigger question of timing not just `ss-install-wordpress-mu-plugins` but really any ss core bash script since this issue could probably apply to any ss core cron jobs...

Really, I don't see how we could adjust the specific time of a certain cron job(s). It would get messy fast, as soon as we stray away from hardcoding the root crontab. It is the one file that truly should be 100% harcoded.

Perhaps a temporary solution would be changing the server timezone, e.g. `SS_TIMEZONE` option in `ss-config`... however I'd much rather figure out a way to avoid such outages.

**Comment by jessuppi** [comment]
A few updates on this:

We changed `ss-install-wordpress-mu-plugins` to only run every few days now, instead of daily. Keep in mind that (for now at least) you can also adjust the intervals of scripts in your `ss-config` file too.

Also, SlickStack has greatly reduced the number of MU plugins installed by default, so there's a lot less bloat.

I'm still not sure how we could reliably enable users to choose the time they want for a specific script to run, since the root crontab is hardcoded to only run our cron files under `/var/www/crons/` ...

Ref: https://github.com/littlebizzy/slickstack/blob/master/crons/00-crontab.txt

I think for now we are just going to have to close this as a "wontfix" feature request, and prioritize making everything in SlickStack run a smoothly as possible so that this isn't even an issue going forward hopefully.
