### ISSUE TITLE
ss-clean removes a theme file - "stats.php" as file name

### ISSUE THREAD

**Issue by hxinen** [littlebizzy/slickstack#8]
Hi, 

I figured out that this cron job 5-cron-half-daily keeps on deleting a file from a theme my site uses.
`find /var/www/html/ -name "stats.php" -type f -delete`

Every delete, the site will be unaccessible and I will have to manually upload the stats.php file on my themes folder. Is there a way for me to exclude this stats.php from getting deleted?

Thank you so much.

======
Works great with $ sudo chattr +i stats.php

**Comment by jessuppi** [comment]
Okay we've removed that rule from `ss-clean`

Got a little over ambitious last week on malware removals due to an increase in plugin infections, we'll probably have to relax some of the other filename deletions as well.

https://github.com/littlebizzy/slickstack/commit/caf5f4ed5645a3a6a8e22e56442dcbd147e59f70
