### ISSUE TITLE
Possible to have a MySQL-only version of SlickStack server?

### ISSUE THREAD

**Issue by jessuppi** [littlebizzy/slickstack#94]
I'm reposting this on behalf of a request from one of our communities:

"...one of the things I like the most about SlickStack is its constant evolution. However, in my case I think I am losing mysql optimizations because I use a remote database. I have 2 vps: webserver & dbserver, the webserver runs SS and the dbserver mysql only.

As you know SS can be installed without mysql but it would be possible to install SS without anything but mysql? I mean, a stack that only runs ss-install-mysql, ss-optimize-database, ss-perms-mysql, swapfile and that can be updated like the websever."

**Comment by jessuppi** [comment]
After careful consideration, I don't think we are going to proceed with this for now.

The challenges that this would entail:

- the MySQL (SlickStack) server would have to allow public access to database ports over TCP, which means less security hardcoding would be possible in our default server configuration, etc
- because of the public access required, we would need additional security features such as whitelisting connections from only certain IP addresses and such... meaning more dynamic settings for niche use cases (we don't want this)

Anyway, I believe `ss-optimize-database` should still work actually for remote databases, or we could get it working.

And lastly, the cost of remote managed database servers are so cheap these days. Based on all the reasons here, I'm going to close this feature request for now... but future comments are welcome.

**Comment by rahnd** [comment]
Hi Jesse!

I read that you are now set up for multisite. I think that is awesome! You may not remember me but I was happily going along using your stuff, but then I had to use multisite due to me business model. I was the one exception at the time where you said "yeah that makes sense."

I have settled down at Amazon and other spots, but at some point I'd like to consider making my way back to your service - it was always excellent and your interaction with me was super! I also hired you from Upwork and you saved my site and we moved over to your service!

Congratulations again, I'll be keeping my eyes open for an opportunity to get back to your stuff!

David Rahn
________________________________
