### ISSUE TITLE
locked out of ssh using sudo user/psw

### ISSUE THREAD

**Issue by kebs19** [littlebizzy/slickstack#97]
hey there
I just installed slickslack on a Oracle Cloud VPN, and when I finished the setup, I'm locked out of the SSH.
I'm using the sudo user and password set up at the tutorial, and the port also set up there. 
I'm using WinSCP and it says "Authentication failed.".
Tried using the SFTP user/psw, but didn't work.
Since I'm using port 2000, the tutorial closed access to the port 22, so I'm locked out.

Is there a way to set WinSCP or a combination of user/psw or maybe a key I can use to access the system?
thanks

**Comment by kebs19** [comment]
I know what went wrong. I set the system to use SSH keys but the system hung me up before I could set it correctly.
The set-up wizard should ask for the public SSH key when you select the option to use ssh keys.... 
(or at least make some documentation available, as the 'doc' link is a mere list of faqs)

**Comment by jessuppi** [comment]
Thanks for reporting @kebs19 

Yes the SSH keys feature was previously reported broken a few months back. I will try to prioritize fixing this, since it is one of the most critical features (that said, many of our users don't seem to use SSH keys per se).

As far as when to upload the public key, thanks for the idea, I will try to brainstorm what would be the simplest solution.

**Comment by jessuppi** [comment]
Okay, this should be solved now. The setup wizard in `ss-install` will now prompt the user to upload their preferred public key under `/var/www/auth/id_rsa.pub` directory if none exists, or otherwise will generate a private/public key pair.

Also related (file permissions): https://github.com/littlebizzy/slickstack/issues/81

The wizard is still a bit janky, but SSH keys should work now.

I haven't had time to test this thoroughly esp. on various types of computers (e.g. Windows, etc) so we'd really appreciate feedback from users on this feature.

Please comment below if anyone notices this is still not work properly, or join our chat rooms.
